"""
Build European Bird Taxonomy

Fetches eBird taxonomy (public API) and cross-references with the European
species list (from Avibase) to generate taxonomy-europe.js.

Usage:
    python build-europe-taxonomy.py
    python build-europe-taxonomy.py --refresh   # re-download eBird taxonomy
"""

import os
import sys
import json
import urllib.request
import re
from collections import OrderedDict

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
EBIRD_CACHE = os.path.join(BASE_DIR, "ebird-taxonomy-full.json")
EUR_SPECIES = os.path.join(BASE_DIR, "european-species.json")
OUTPUT = os.path.join(BASE_DIR, "taxonomy-europe.js")

EBIRD_URL = "https://api.ebird.org/v2/ref/taxonomy/ebird?fmt=json&cat=species"
AVIBASE_URL = "https://avibase.bsc-eoc.org/checklist.jsp?region=EUR&list=clements"


def fetch_ebird_taxonomy(force=False):
    """Fetch full eBird taxonomy, cache locally."""
    if not force and os.path.exists(EBIRD_CACHE):
        print(f"Using cached eBird taxonomy from {EBIRD_CACHE}")
        with open(EBIRD_CACHE, "r") as f:
            return json.load(f)

    print("Fetching eBird taxonomy...")
    req = urllib.request.Request(EBIRD_URL)
    with urllib.request.urlopen(req, timeout=120) as resp:
        data = json.loads(resp.read().decode("utf-8"))

    with open(EBIRD_CACHE, "w") as f:
        json.dump(data, f)
    print(f"Cached {len(data)} species to {EBIRD_CACHE}")
    return data


def fetch_european_species(force=False):
    """Fetch European species list from Avibase, cache locally."""
    if not force and os.path.exists(EUR_SPECIES):
        print(f"Using cached European species list from {EUR_SPECIES}")
        with open(EUR_SPECIES, "r") as f:
            return json.load(f)

    print("Fetching Avibase European checklist...")
    req = urllib.request.Request(AVIBASE_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        html = resp.read().decode("utf-8", errors="replace")

    sci_names = re.findall(r"<i[^>]*>([A-Z][a-z]+ [a-z]+)</i>", html)
    seen = set()
    unique = []
    for name in sci_names:
        if name not in seen:
            seen.add(name)
            unique.append(name)

    with open(EUR_SPECIES, "w") as f:
        json.dump(unique, f, indent=2)
    print(f"Cached {len(unique)} European species to {EUR_SPECIES}")
    return unique


def build_taxonomy(ebird_data, euro_species):
    """Cross-reference European species with eBird taxonomy."""
    # Build lookup by scientific name
    ebird_lookup = {}
    for sp in ebird_data:
        ebird_lookup[sp["sciName"]] = sp

    # Match European species to eBird records
    matched = []
    unmatched = []
    for sci in euro_species:
        if sci in ebird_lookup:
            matched.append(ebird_lookup[sci])
        else:
            unmatched.append(sci)

    if unmatched:
        print(f"Warning: {len(unmatched)} species not found in eBird taxonomy:")
        for name in unmatched[:20]:
            print(f"  - {name}")
        if len(unmatched) > 20:
            print(f"  ... and {len(unmatched) - 20} more")

    print(f"Matched {len(matched)} of {len(euro_species)} European species")

    # Sort by taxonomic order
    matched.sort(key=lambda sp: sp.get("taxonOrder", 99999))

    # Group by order -> family
    taxonomy = OrderedDict()
    for sp in matched:
        order = sp["order"]
        fam_sci = sp["familySciName"]
        fam_com = sp["familyComName"]

        if order not in taxonomy:
            taxonomy[order] = OrderedDict()
        if fam_sci not in taxonomy[order]:
            taxonomy[order][fam_sci] = {
                "familyComName": fam_com,
                "species": [],
            }
        taxonomy[order][fam_sci]["species"].append({
            "sci": sp["sciName"],
            "en": sp["comName"],
        })

    return taxonomy


def write_js(taxonomy):
    """Write taxonomy-europe.js in same format as TAXONOMY_ICELAND."""
    lines = []
    lines.append("// Auto-generated by build-europe-taxonomy.py")
    lines.append("// Do not edit manually — run: python build-europe-taxonomy.py")

    total_species = sum(
        len(fam["species"])
        for order_fams in taxonomy.values()
        for fam in order_fams.values()
    )
    total_families = sum(len(fams) for fams in taxonomy.values())
    lines.append(f"// {len(taxonomy)} orders, {total_families} families, {total_species} species")
    lines.append("")
    lines.append("const TAXONOMY_EUROPE = [")

    for order, families in taxonomy.items():
        # Use first family's common name as a rough order common name
        first_fam = next(iter(families.values()))
        order_common = first_fam["familyComName"] if len(families) == 1 else order
        lines.append(f'  {{ order: "{order}", orderCommon: "{order}", families: [')
        for fam_sci, fam_data in families.items():
            fam_com_escaped = fam_data["familyComName"].replace('"', '\\"')
            lines.append(f'    {{ family: "{fam_sci}", familyCommon: "{fam_com_escaped}", species: [')
            for sp in fam_data["species"]:
                sci_escaped = sp["sci"].replace('"', '\\"')
                en_escaped = sp["en"].replace('"', '\\"')
                lines.append(f'      {{ sci: "{sci_escaped}", en: "{en_escaped}" }},')
            lines.append("    ]},")
        lines.append("  ]},")

    lines.append("];")
    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written {total_species} species to {OUTPUT}")


def main():
    force = "--refresh" in sys.argv

    ebird_data = fetch_ebird_taxonomy(force)
    euro_species = fetch_european_species(force)
    taxonomy = build_taxonomy(ebird_data, euro_species)
    write_js(taxonomy)


if __name__ == "__main__":
    main()
