"""
Photo Scanner for Bird Browser

Run this whenever you add/remove photos:
    python scan-photos.py
"""

import os
import json
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(BASE_DIR, "photo-manifest.js")

EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

REGIONS = [
    ("photos", "PHOTO_MANIFEST_ICELAND", "iceland"),
    ("photos-florida", "PHOTO_MANIFEST_FLORIDA", "florida"),
    ("photos-europe", "PHOTO_MANIFEST_EUROPE", "europe"),
]

output_parts = [f"// Auto-generated by scan-photos.py — {datetime.now().isoformat()}\n"]

for photos_dir_name, var_name, location in REGIONS:
    photos_dir = os.path.join(BASE_DIR, photos_dir_name)
    manifest = {}

    if os.path.isdir(photos_dir):
        for dirname in sorted(os.listdir(photos_dir)):
            dirpath = os.path.join(photos_dir, dirname)
            if not os.path.isdir(dirpath):
                continue

            sci_name = dirname.replace("_", " ")
            files = sorted(
                f for f in os.listdir(dirpath)
                if os.path.splitext(f)[1].lower() in EXTENSIONS
            )

            if files:
                manifest[sci_name] = [{"file": f"{photos_dir_name}/{dirname}/{f}", "location": location} for f in files]

    total_photos = sum(len(v) for v in manifest.values())
    total_species = len(manifest)

    output_parts.append(f"// {var_name}: {total_species} species, {total_photos} photos\n")
    output_parts.append(f"const {var_name} = {json.dumps(manifest, indent=2)};\n\n")
    print(f"{var_name}: {total_photos} photos across {total_species} species")

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write("".join(output_parts))

print(f"Written to {OUTPUT}")
