#!/usr/bin/env node
/**
 * Photo Scanner for Icelandic Birds Browser
 * 
 * Run this whenever you add/remove photos:
 *   node scan-photos.js
 * 
 * It scans the /photos folder and generates photo-manifest.js
 * which the app reads to know what images are available.
 */

const fs = require('fs');
const path = require('path');

const PHOTOS_DIR = path.join(__dirname, 'photos');
const OUTPUT = path.join(__dirname, 'photo-manifest.js');

const EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp']);

const manifest = {};

const species = fs.readdirSync(PHOTOS_DIR).filter(d => 
  fs.statSync(path.join(PHOTOS_DIR, d)).isDirectory()
);

for (const dir of species) {
  const sciName = dir.replace(/_/g, ' ');
  const dirPath = path.join(PHOTOS_DIR, dir);
  
  const files = fs.readdirSync(dirPath)
    .filter(f => EXTENSIONS.has(path.extname(f).toLowerCase()))
    .sort();
  
  if (files.length > 0) {
    manifest[sciName] = files.map(f => ({
      file: `photos/${dir}/${f}`,
    }));
  }
}

const totalPhotos = Object.values(manifest).reduce((s, arr) => s + arr.length, 0);
const totalSpecies = Object.keys(manifest).length;

const output = `// Auto-generated by scan-photos.js — ${new Date().toISOString()}
// ${totalSpecies} species, ${totalPhotos} photos
const PHOTO_MANIFEST = ${JSON.stringify(manifest, null, 2)};
`;

fs.writeFileSync(OUTPUT, output);
console.log(`✓ Scanned ${totalPhotos} photos across ${totalSpecies} species`);
console.log(`✓ Written to ${OUTPUT}`);
