"""
Photo Scanner for Icelandic Birds Browser

Run this whenever you add/remove photos:
    python scan-photos.py
"""

import os
import json
from datetime import datetime

PHOTOS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "photos")
OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "photo-manifest.js")

EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

manifest = {}

for dirname in sorted(os.listdir(PHOTOS_DIR)):
    dirpath = os.path.join(PHOTOS_DIR, dirname)
    if not os.path.isdir(dirpath):
        continue

    sci_name = dirname.replace("_", " ")
    files = sorted(
        f for f in os.listdir(dirpath)
        if os.path.splitext(f)[1].lower() in EXTENSIONS
    )

    if files:
        manifest[sci_name] = [{"file": f"photos/{dirname}/{f}"} for f in files]

total_photos = sum(len(v) for v in manifest.values())
total_species = len(manifest)

output = (
    f"// Auto-generated by scan-photos.py — {datetime.now().isoformat()}\n"
    f"// {total_species} species, {total_photos} photos\n"
    f"const PHOTO_MANIFEST = {json.dumps(manifest, indent=2)};\n"
)

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write(output)

print(f"Done! {total_photos} photos across {total_species} species")
print(f"Written to {OUTPUT}")
