// Auto-generated by Export Settings in the app.
// Do not edit manually.
var SAVED_SETTINGS = {
  "sp:Larus_argentatus": "{\"positions\":[{\"x\":2.700949367088616,\"y\":0,\"w\":67.01898734177215,\"h\":100},{\"x\":44.414556962025316,\"y\":0,\"w\":39,\"h\":47},{\"x\":50.26898734177215,\"y\":47.22641509433962,\"w\":39,\"h\":47}],\"hidden\":[3,1,2],\"crops\":{},\"mood\":\"midnight\"}"
};
